Deploy Remote Resources
Provision remote resources on Cloudflare and DigitalOcean using
Terraform. Configure Cloudflare DNS and create a DigitalOcean Droplet
running the containerized application behind a *Caddy* server. Extend
helper scripts for deployment and destruction of resources, by default.

diff --git a/cli/deploy b/cli/deploy
--- a/cli/deploy
+++ b/cli/deploy
@@ -1,23 +1,61 @@
-source "$(dirname "${BASH_SOURCE[0]}")/utils/environment"
+source "$(dirname "${BASH_SOURCE[0]}")/utils/deployment"
 
 deploy() {
-    usage() {
-        echo "Usage: $0 [options]"
-        echo "Options:"
-        echo "  --namespace             Specify the GitHub namespace for image"
-        echo "  --package               Specify the name of image package."
-        echo "  --help, -h              Show this help message."
-    }
+    local loc
+    local approve
+    parse_environment_args "$@" || return 1
+    loc=$(parse_local_arg "$@") || return 1
+    approve=$(parse_approve_arg "$@") || return 1
 
-    load_env
+    if [[ "$loc" = false ]]; then
+        echo "Initializing Terraform..."
+        cd "infra" || return 1
 
-    while [[ "$1" != "" ]]; do
-        case "$1" in
-            --help | -h) usage; return 0;;
-            *) echo "Unknown option: $1"; return 1;;
-        esac
-        shift
-    done
+        terraform init -reconfigure \
+            -backend-config="prefix=$ENVIRONMENT"
+        if [[ $? -ne 0 ]]; then
+            echo "Failed to initialize Terraform."
+            return 1
+        fi
+
+        echo "Deploying to production environment..."
+        terraform plan -out=tfplan \
+            -var "namespace=$FOLIO_APP_ACCOUNT" \
+            -var "domain=$FOLIO_APP_DOMAIN" \
+            -var "dns_zone=$FOLIO_CF_DNS_ZONE" \
+            -var "ssh_port=$FOLIO_SSH_PORT" \
+            -var "acme_email=$FOLIO_ACME_EMAIL" \
+            -var "ssh_public_key_file=$FOLIO_PUBLIC_KEY_FILE" \
+            -var "cf_token=$FOLIO_CF_TOKEN" \
+            -var "do_token=$FOLIO_DO_TOKEN"
+        if [[ $? -ne 0 ]]; then
+            echo "Failed to create Terraform plan."
+            return 1
+        fi
+
+        if [[ "$approve" != true ]]; then
+            echo "Deploy $ENVIRONMENT configuration to $FOLIO_APP_DOMAIN? (y/n)"
+            read -r response
+            if [[ ! "$response" =~ ^[Yy]$ ]]; then
+                echo
+                echo "Deployment aborted."
+                return 0
+            fi
+        fi
+
+        echo "Applying Terraform plan..."
+        terraform apply tfplan
+        if [[ $? -ne 0 ]]; then
+            echo "Failed to apply Terraform plan."
+            return 1
+        fi
+
+        cd .. || return 1
+        echo
+        echo "Application is running at https://$FOLIO_APP_DOMAIN"
+        echo "Deployment of $ENVIRONMENT completed successfully."
+        return 0
+    fi
 
     if docker image inspect "$FOLIO_APP_REPO:latest" > /dev/null 2>&1; then
         docker run -d \
