Deploy Remote Resources
Provision remote resources on Cloudflare and DigitalOcean using
Terraform. Configure Cloudflare DNS and create a DigitalOcean Droplet
running the containerized application behind a *Caddy* server. Extend
helper scripts for deployment and destruction of resources, by default.

diff --git a/cli/deploy b/cli/deploy
--- a/cli/deploy
+++ b/cli/deploy
@@ -1,7 +1,61 @@
-source "$(dirname "${BASH_SOURCE[0]}")/utils/environment"
+source "$(dirname "${BASH_SOURCE[0]}")/utils/deployment"
 
 deploy() {
-    load_env
+    local loc
+    local approve
+    parse_environment_args "$@" || return 1
+    loc=$(parse_local_arg "$@") || return 1
+    approve=$(parse_approve_arg "$@") || return 1
+
+    if [[ "$loc" = "false" ]]; then
+        echo "Initializing Terraform..."
+
+        terraform -chdir=infra init -reconfigure \
+            -backend-config="prefix=$ENVIRONMENT"
+        if [[ $? -ne 0 ]]; then
+            echo "Failed to initialize Terraform."
+            return 1
+        fi
+
+        echo "Deploying to production environment..."
+        terraform -chdir=infra plan -out=tfplan \
+            -var "environment=$ENVIRONMENT" \
+            -var "namespace=$FOLIO_APP_ACCOUNT" \
+            -var "domain=$FOLIO_APP_DOMAIN" \
+            -var "dns_zone=$FOLIO_CF_DNS_ZONE" \
+            -var "ssh_port=$FOLIO_SSH_PORT" \
+            -var "acme_email=$FOLIO_ACME_EMAIL" \
+            -var "ssh_key_id=$FOLIO_SSH_KEY_ID" \
+            -var "ssh_public_key_file=$FOLIO_PUBLIC_KEY_FILE" \
+            -var "cf_token=$FOLIO_CF_TOKEN" \
+            -var "do_token=$FOLIO_DO_TOKEN"
+        if [[ $? -ne 0 ]]; then
+            echo "Failed to create Terraform plan."
+            return 1
+        fi
+
+        if [[ "$approve" != "true" ]]; then
+            echo "Deploy $ENVIRONMENT configuration to $FOLIO_APP_DOMAIN? (y/n)"
+            read -r response
+            if [[ ! "$response" =~ ^[Yy]$ ]]; then
+                echo
+                echo "Deployment aborted."
+                return 0
+            fi
+        fi
+
+        echo "Applying Terraform plan..."
+        terraform -chdir=infra apply tfplan
+        if [[ $? -ne 0 ]]; then
+            echo "Failed to apply Terraform plan."
+            return 1
+        fi
+
+        echo
+        echo "Application is running at https://$FOLIO_APP_DOMAIN"
+        echo "Deployment of $ENVIRONMENT completed successfully."
+        return 0
+    fi
 
     if docker image inspect "$FOLIO_APP_REPO:latest" > /dev/null 2>&1; then
         docker run -d \
diff --git a/cli/destroy b/cli/destroy
--- a/cli/destroy
+++ b/cli/destroy
@@ -1,4 +1,61 @@
+source "$(dirname "${BASH_SOURCE[0]}")/utils/deployment"
+
 destroy() {
+    local loc
+    local approve
+    parse_environment_args "$@" || return 1
+    loc=$(parse_local_arg "$@") || return 1
+    approve=$(parse_approve_arg "$@") || return 1
+
+    if [[ "$loc" = "false" ]]; then
+        echo "Initializing Terraform..."
+
+        terraform -chdir=infra init -reconfigure \
+            -backend-config="prefix=$ENVIRONMENT"
+        if [[ $? -ne 0 ]]; then
+            echo "Failed to initialize Terraform."
+            return 1
+        fi
+
+        echo
+        echo "Destroying production environment..."
+        terraform -chdir=infra plan -destroy -out=tfplan \
+            -var "environment=$ENVIRONMENT" \
+            -var "namespace=$FOLIO_APP_ACCOUNT" \
+            -var "domain=$FOLIO_APP_DOMAIN" \
+            -var "dns_zone=$FOLIO_CF_DNS_ZONE" \
+            -var "ssh_port=$FOLIO_SSH_PORT" \
+            -var "acme_email=$FOLIO_ACME_EMAIL" \
+            -var "ssh_key_id=$FOLIO_SSH_KEY_ID" \
+            -var "ssh_public_key_file=$FOLIO_PUBLIC_KEY_FILE" \
+            -var "cf_token=$FOLIO_CF_TOKEN" \
+            -var "do_token=$FOLIO_DO_TOKEN "
+        if [[ $? -ne 0 ]]; then
+            echo "Failed to create Terraform destroy plan."
+            return 1
+        fi
+
+        if [[ "$approve" != "true" ]]; then
+            echo "Destroy $FOLIO_APP_DOMAIN deployment? (y/n)"
+            read -r response
+            echo
+            if [[ ! "$response" =~ ^[Yy]$ ]]; then
+                echo "Deployment aborted."
+                return 0
+            fi
+        fi
+
+        echo "Applying Terraform destroy plan..."
+        terraform -chdir=infra apply tfplan
+        if [[ $? -ne 0 ]]; then
+            echo "Failed to destroy deployment."
+            return 1
+        fi
+
+        echo "Deployment destroyed successfully."
+        return 0
+    fi
+
     if [[ -n "$(docker ps -q -f name=folio)" ]]; then
         echo "Stopping and removing the application container..."
         docker stop folio > /dev/null
diff --git a/cli/test b/cli/test
--- a/cli/test
+++ b/cli/test
@@ -4,15 +4,22 @@ test() {
         echo "  $0 [options]"
         echo "  $0 [options] <test-path>"
         echo "Options:"
+        echo "  --cli               Run command tests"
+        echo "  --infra             Run infrastructure tests"
+        echo "  --terraform         Run Terraform tests"
         echo "  --filter, -e        Specify regex to filter tests by name"
         echo "  --help, -h          Show this help message"
     }
 
     local test_path=""
     local test_filter=""
+    local flags=""
     while [[ "$1" != "" ]]; do
         case "$1" in
             --help | -h ) usage; return 0;;
+            --cli ) flags+="c";;
+            --infra ) flags+="i";;
+            --terraform ) flags+="t";;
             --filter | -e ) test_filter="$2"; shift;;
             * ) if [[ -z "$test_path" ]]; then test_path="$1"
                 else echo "Too many arguments provided: $1"; usage; return 1
@@ -20,6 +27,13 @@ test() {
         esac
         shift
     done
+
+    if [[ "$flags" == *t* ]]; then
+        if [[ -n "$test_path" ]] || [[ -n "$test_filter" ]]; then
+            echo "Error: Terraform tests cannot be filtered by path or name."
+            return 1
+        fi
+    fi
 
     local os="$(uname -s)"
     local root="$(pwd)"
@@ -38,19 +52,78 @@ test() {
         filter_args=("-f" "$test_filter")
     fi
 
-    echo
-    echo "Running command BATS tests..."
-    docker run --rm -it \
-        --name folio-tests-bats \
-        -v "$root:/code" \
-        bats/bats:latest \
-        "${filter_args[@]}" \
-        "cli/tests/$test_path"
+    failures=$((0))
+    if [[ -z "$flags" ]] || [[ "$flags" == *c* ]]; then
+        echo
+        local path="cli/tests/$test_path"
+        if [[ -d "$path" ]] || [[ -f "$path" ]]; then
+            echo "Running command line interface BATS tests..."
+            docker run --rm -it \
+                --name folio-tests-bats \
+                -v "$root:/code" \
+                bats/bats:latest \
+                "${filter_args[@]}" \
+                "$path"
+            if [[ $? -eq 0 ]];  then
+                echo "Command line interface BATS tests passed successfully."
+            else
+                echo "Command line interface BATS tests failed."
+                failures=$((failures + 1))
+            fi
+        else
+            echo "No command line interface tests found at path: $path"
+        fi
+    fi
 
-    if [[ $? -eq 0 ]];  then
-        echo "BATS tests passed successfully."
-    else
-        echo "BATS tests failed."
+    if [[ -z "$flags" ]] || [[ "$flags" == *i* ]]; then
+        echo
+        local path="infra/tests/$test_path"
+        if [[ -d "$path" ]] || [[ -f "$path" ]]; then
+            echo "Running infrastructure BATS tests..."
+            docker run --rm -it \
+                --name folio-tests-bats \
+                -v "$root:/code" \
+                bats/bats:latest \
+                "${filter_args[@]}" \
+                "$path"
+            if [[ $? -eq 0 ]];  then
+                echo "Infrastructure BATS tests passed successfully."
+            else
+                echo "Infrastructure BATS tests failed."
+                failures=$((failures + 1))
+            fi
+        else
+            echo "No infrastructure tests found at path: $path"
+        fi
+    fi
+
+    if [[ -z "$flags" ]] || [[ "$flags" == *i* ]] || [[ "$flags" == *t* ]]; then
+        if [[ -z "$test_filter" ]] && [[ -z "$test_path" ]]; then
+            echo
+            echo "Running infrastructure Terraform tests..."
+            export TF_DATA_DIR="../.tmp/.terraform"
+            terraform -chdir=infra init -backend=false
+            if [[ $? -ne 0 ]]; then
+                echo "Failed to initialize Terraform."
+                failures=$((failures + 1))
+            fi
+            terraform -chdir=infra test
+            if [[ $? -eq 0 ]]; then
+                echo
+                echo "Terraform tests passed successfully."
+            else
+                echo
+                echo "Terraform tests failed."
+                failures=$((failures + 1))
+            fi
+        fi
+    fi
+
+    echo
+    if [[ $failures -gt 0 ]]; then
+        echo -e "\033[0;31m$failures test suite(s) failed.\033[0m"
         return 1
+    else
+        echo "All tests passed successfully."
     fi
 }
