Set CI/CD Commit Status During, After Test
When test, create an CI/CD pipeline commit status based on the current
state of testing. Abort testing if the commit status is already set to
avoid concurrent testing.

diff --git a/cli/test b/cli/test
--- a/cli/test
+++ b/cli/test
@@ -1,3 +1,6 @@
+source "$(dirname "${BASH_SOURCE[0]}")/utils/environment"
+source "$(dirname "${BASH_SOURCE[0]}")/status"
+
 test() {
     usage() {
         echo "Usage:"
@@ -8,12 +11,21 @@ test() {
         echo "  --infra             Run infrastructure tests"
         echo "  --terraform         Run Terraform tests"
         echo "  --filter, -e        Specify regex to filter tests by name"
+        echo "  --set-status        Set the commit status of CI/CD pipeline"
+        echo "  --force -f          Force test even if a status is already set"
+        echo "  --gh-token          Specify the GitHub API token."
         echo "  --help, -h          Show this help message"
+        echo "Environment Variables:"
+        echo "  FOLIO_GH_TOKEN      GitHub API token."
     }
+
+    load_env
 
     local test_path=""
     local test_filter=""
     local flags=""
+    local set_status=false
+    local force=false
     while [[ "$1" != "" ]]; do
         case "$1" in
             --help | -h ) usage; return 0;;
@@ -21,6 +33,9 @@ test() {
             --infra ) flags+="i";;
             --terraform ) flags+="t";;
             --filter | -e ) test_filter="$2"; shift;;
+            --set-status ) set_status=true;;
+            --force | -f ) force=true;;
+            --gh-token ) FOLIO_GH_TOKEN="$2"; shift;;
             * ) if [[ -z "$test_path" ]]; then test_path="$1"
                 else echo "Too many arguments provided: $1"; usage; return 1
                 fi;;
@@ -28,12 +43,57 @@ test() {
         shift
     done
 
+    if ( \
+        [[ -n "$test_path" || -n "$test_filter" ]] \
+            && [[ "$set_status" == "true" ]] \
+    ); then
+        echo "Error: Cannot set status when running subset of tests."
+        usage
+        return 1
+    fi
+
     if [[ "$flags" == *t* ]]; then
         if [[ -n "$test_path" ]] || [[ -n "$test_filter" ]]; then
             echo "Error: Terraform tests cannot be filtered by path or name."
             return 1
         fi
     fi
+
+    if [[ "$set_status" == "true" ]]; then
+        if [[ -z "$FOLIO_GH_TOKEN" ]]; then
+            echo "GitHub token required to set commit status."
+            return 1
+        fi
+
+        local status
+        status=$(status --self)
+        if [[ $? -ne 0 ]]; then
+            echo "Failed to retrieve current commit status."
+            return 1
+        fi
+
+        if [[ "$status" != "none" ]]; then
+            echo "Commit already tested: $status."
+            if [[ "$force" != "true" ]]; then
+                echo "Aborting tests to avoid concurrent runs."
+                return 1
+            fi
+            echo "Forcing tests despite existing status."
+        fi
+    fi
+
+    update_status() {
+        if [[ "$set_status" == "false" ]]; then return 0; fi
+        status set --self "$1" --description "Automated tests $2." \
+            > /dev/null 2>&1
+        if [[ $? -ne 0 ]]; then
+            echo "Failed to update commit status: $1."
+            return 1
+        fi
+        echo "Commit status updated to: $1."
+    }
+
+    update_status "pending" "started" || return 1
 
     local os="$(uname -s)"
     local root="$(pwd)"
@@ -122,8 +182,10 @@ test() {
     echo
     if [[ $failures -gt 0 ]]; then
         echo -e "\033[0;31m$failures test suite(s) failed.\033[0m"
+        update_status "failure" "failed"
         return 1
     else
         echo "All tests passed successfully."
+        update_status "success" "completed successfully" || return 1
     fi
 }
